# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1357, 811)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-10, -10, 1366, 743))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame.setFont(font)
        self.frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.vid = QtWidgets.QLabel(self.frame)
        self.vid.setGeometry(QtCore.QRect(60, 150, 721, 421))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vid.sizePolicy().hasHeightForWidth())
        self.vid.setSizePolicy(sizePolicy)
        self.vid.setStyleSheet("QLabel {\n"
"    background-color: qlineargradient(\n"
"        spread:pad, x1:0, y1:0, x2:0, y2:1, /* Gradasi vertikal */\n"
"        stop:0 rgba(0, 0, 0, 245),         /* Hitam di atas */\n"
"        stop:0.3 rgb(32, 33, 36),          /* Peralihan dari hitam ke warna tengah */\n"
"        stop:0.7 rgb(32, 33, 36),          /* Warna tengah berlangsung lebih lama */\n"
"        stop:1 rgba(0, 0, 0, 245)          /* Hitam di bawah */\n"
"    );\n"
"    border: 2px solid rgb(32, 33, 36);\n"
"    color: white;\n"
"}")
        self.vid.setFrameShape(QtWidgets.QFrame.Box)
        self.vid.setText("")
        self.vid.setScaledContents(True)
        self.vid.setObjectName("vid")
        self.sentence = QtWidgets.QLabel(self.frame)
        self.sentence.setGeometry(QtCore.QRect(820, 210, 501, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sentence.sizePolicy().hasHeightForWidth())
        self.sentence.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.sentence.setFont(font)
        self.sentence.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.sentence.setStyleSheet("QLabel {\n"
"    border-radius: 5px;            /* Border radius 5px */\n"
"    border:1px solid;\n"
"}")
        self.sentence.setFrameShape(QtWidgets.QFrame.Box)
        self.sentence.setText("")
        self.sentence.setTextFormat(QtCore.Qt.PlainText)
        self.sentence.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sentence.setObjectName("sentence")
        self.kata = QtWidgets.QLabel(self.frame)
        self.kata.setGeometry(QtCore.QRect(820, 180, 111, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kata.sizePolicy().hasHeightForWidth())
        self.kata.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.kata.setFont(font)
        self.kata.setObjectName("kata")
        self.character = QtWidgets.QLabel(self.frame)
        self.character.setGeometry(QtCore.QRect(820, 150, 111, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.character.sizePolicy().hasHeightForWidth())
        self.character.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.character.setFont(font)
        self.character.setObjectName("character")
        self.chara = QtWidgets.QLabel(self.frame)
        self.chara.setGeometry(QtCore.QRect(930, 150, 111, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chara.sizePolicy().hasHeightForWidth())
        self.chara.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.chara.setFont(font)
        self.chara.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.chara.setText("")
        self.chara.setObjectName("chara")
        self.dele = QtWidgets.QPushButton(self.frame)
        self.dele.setGeometry(QtCore.QRect(1070, 150, 71, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dele.sizePolicy().hasHeightForWidth())
        self.dele.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dele.setFont(font)
        self.dele.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/delete-left-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dele.setIcon(icon)
        self.dele.setIconSize(QtCore.QSize(40, 45))
        self.dele.setObjectName("dele")
        self.clear = QtWidgets.QPushButton(self.frame)
        self.clear.setGeometry(QtCore.QRect(1160, 150, 71, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear.sizePolicy().hasHeightForWidth())
        self.clear.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.clear.setFont(font)
        self.clear.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/eraser-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clear.setIcon(icon1)
        self.clear.setIconSize(QtCore.QSize(40, 30))
        self.clear.setObjectName("clear")
        self.speakk = QtWidgets.QPushButton(self.frame)
        self.speakk.setGeometry(QtCore.QRect(1250, 150, 71, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speakk.sizePolicy().hasHeightForWidth())
        self.speakk.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.speakk.setFont(font)
        self.speakk.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/head-side-cough-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.speakk.setIcon(icon2)
        self.speakk.setIconSize(QtCore.QSize(40, 30))
        self.speakk.setObjectName("speakk")
        self.camera = QtWidgets.QComboBox(self.frame)
        self.camera.setGeometry(QtCore.QRect(60, 580, 171, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera.sizePolicy().hasHeightForWidth())
        self.camera.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.camera.setFont(font)
        self.camera.setStyleSheet("QComboBox{\n"
"border-radius:5px;\n"
"}")
        self.camera.setEditable(False)
        self.camera.setIconSize(QtCore.QSize(20, 20))
        self.camera.setObjectName("camera")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon/video-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.camera.addItem(icon3, "")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icon/webcam.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.camera.addItem(icon4, "")
        self.bahasa = QtWidgets.QComboBox(self.frame)
        self.bahasa.setGeometry(QtCore.QRect(250, 580, 171, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bahasa.sizePolicy().hasHeightForWidth())
        self.bahasa.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bahasa.setFont(font)
        self.bahasa.setStyleSheet("QComboBox{\n"
"border-radius:5px;\n"
"}")
        self.bahasa.setObjectName("bahasa")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icon/flag.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bahasa.addItem(icon5, "")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icon/united-kingdom.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bahasa.addItem(icon6, "")
        self.logo = QtWidgets.QLabel(self.frame)
        self.logo.setGeometry(QtCore.QRect(30, 30, 261, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("icon/picture/cb57dd40-acdd-48e5-a793-b2698cc3d0ed-removebg-preview.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.check_cam = QtWidgets.QCheckBox(self.frame)
        self.check_cam.setGeometry(QtCore.QRect(400, 500, 51, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_cam.sizePolicy().hasHeightForWidth())
        self.check_cam.setSizePolicy(sizePolicy)
        self.check_cam.setStyleSheet("    QCheckBox {\n"
"        background-color: rgb(255, 255, 255);  /* Warna latar belakang default */\n"
"        border: 1px solid white;\n"
"        border-radius: 25px; /* Setengah dari lebar/tinggi untuk membuat lingkaran */\n"
"        padding: 10px;  /* Tambahkan padding untuk menambah jarak */\n"
"    }\n"
"    QCheckBox::indicator {\n"
"        width: 0px; \n"
"        height: 0px;\n"
"    }\n"
"\n"
"QCheckBox:checked {\n"
"    background-color: rgb(234, 67, 53);\n"
"        color: white;\n"
"        border: 1px solid rgb(234, 67, 53);\n"
"        border-radius: 25px; /* Setengah dari lebar/tinggi untuk membuat lingkaran */\n"
"    }\n"
"")
        self.check_cam.setText("")
        self.check_cam.setIcon(icon3)
        self.check_cam.setIconSize(QtCore.QSize(20, 20))
        self.check_cam.setCheckable(True)
        self.check_cam.setChecked(False)
        self.check_cam.setObjectName("check_cam")
        self.check_hand = QtWidgets.QCheckBox(self.frame)
        self.check_hand.setGeometry(QtCore.QRect(330, 500, 51, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_hand.sizePolicy().hasHeightForWidth())
        self.check_hand.setSizePolicy(sizePolicy)
        self.check_hand.setStyleSheet("    QCheckBox {\n"
"        background-color: rgb(255, 255, 255);  /* Warna latar belakang default */\n"
"        border: 1px solid white;\n"
"        border-radius: 25px; /* Setengah dari lebar/tinggi untuk membuat lingkaran */\n"
"        padding: 10px;  /* Tambahkan padding untuk menambah jarak */\n"
"    }\n"
"    QCheckBox::indicator {\n"
"        width: 0px; \n"
"        height: 0px;\n"
"    }\n"
"\n"
"QCheckBox:checked {\n"
"    background-color: rgb(234, 67, 53);\n"
"        color: white;\n"
"        border: 1px solid rgb(234, 67, 53);\n"
"        border-radius: 25px; /* Setengah dari lebar/tinggi untuk membuat lingkaran */\n"
"    }\n"
"")
        self.check_hand.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icon/hand-point-up-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.check_hand.setIcon(icon7)
        self.check_hand.setIconSize(QtCore.QSize(25, 25))
        self.check_hand.setChecked(False)
        self.check_hand.setAutoRepeat(False)
        self.check_hand.setObjectName("check_hand")
        self.check_speak = QtWidgets.QCheckBox(self.frame)
        self.check_speak.setGeometry(QtCore.QRect(260, 500, 51, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_speak.sizePolicy().hasHeightForWidth())
        self.check_speak.setSizePolicy(sizePolicy)
        self.check_speak.setStyleSheet("    QCheckBox {\n"
"        background-color: rgb(255, 255, 255);  /* Warna latar belakang default */\n"
"        border: 1px solid white;\n"
"        border-radius: 25px; /* Setengah dari lebar/tinggi untuk membuat lingkaran */\n"
"        padding: 6px;  /* Tambahkan padding untuk menambah jarak */\n"
"    }\n"
"    QCheckBox::indicator {\n"
"        width: 0px; \n"
"        height: 0px;\n"
"    }\n"
"\n"
"QCheckBox:checked {\n"
"    background-color: rgb(234, 67, 53);\n"
"        color: white;\n"
"        border: 1px solid rgb(234, 67, 53);\n"
"        border-radius: 25px; /* Setengah dari lebar/tinggi untuk membuat lingkaran */\n"
"    }\n"
"")
        self.check_speak.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icon/volume-high-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.check_speak.setIcon(icon8)
        self.check_speak.setIconSize(QtCore.QSize(25, 25))
        self.check_speak.setChecked(False)
        self.check_speak.setObjectName("check_speak")
        self.check_bright = QtWidgets.QCheckBox(self.frame)
        self.check_bright.setGeometry(QtCore.QRect(540, 500, 51, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_bright.sizePolicy().hasHeightForWidth())
        self.check_bright.setSizePolicy(sizePolicy)
        self.check_bright.setStyleSheet("    QCheckBox {\n"
"        background-color: rgb(255, 255, 255);  /* Warna latar belakang default */\n"
"        border: 1px solid white;\n"
"        border-radius: 25px; /* Setengah dari lebar/tinggi untuk membuat lingkaran */\n"
"        padding: 6px;  /* Tambahkan padding untuk menambah jarak */\n"
"    }\n"
"    QCheckBox::indicator {\n"
"        width: 0px; \n"
"        height: 0px;\n"
"    }\n"
"\n"
"QCheckBox:checked {\n"
"    background-color: rgb(234, 67, 53);\n"
"        color: white;\n"
"        border: 1px solid rgb(234, 67, 53);\n"
"        border-radius: 25px; /* Setengah dari lebar/tinggi untuk membuat lingkaran */\n"
"    }\n"
"")
        self.check_bright.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icon/sun-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.check_bright.setIcon(icon9)
        self.check_bright.setIconSize(QtCore.QSize(25, 25))
        self.check_bright.setChecked(False)
        self.check_bright.setObjectName("check_bright")
        self.check_draw = QtWidgets.QCheckBox(self.frame)
        self.check_draw.setGeometry(QtCore.QRect(470, 500, 51, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_draw.sizePolicy().hasHeightForWidth())
        self.check_draw.setSizePolicy(sizePolicy)
        self.check_draw.setStyleSheet("    QCheckBox {\n"
"        background-color: rgb(255, 255, 255);  /* Warna latar belakang default */\n"
"        border: 1px solid white;\n"
"        border-radius: 25px; /* Setengah dari lebar/tinggi untuk membuat lingkaran */\n"
"        padding: 6px;  /* Tambahkan padding untuk menambah jarak */\n"
"    }\n"
"    QCheckBox::indicator {\n"
"        width: 0px; \n"
"        height: 0px;\n"
"    }\n"
"\n"
"QCheckBox:checked {\n"
"    background-color: rgb(234, 67, 53);\n"
"        color: white;\n"
"        border: 1px solid rgb(234, 67, 53);\n"
"        border-radius: 25px; /* Setengah dari lebar/tinggi untuk membuat lingkaran */\n"
"    }\n"
"")
        self.check_draw.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icon/palette-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.check_draw.setIcon(icon10)
        self.check_draw.setIconSize(QtCore.QSize(25, 25))
        self.check_draw.setObjectName("check_draw")
        self.idle = QtWidgets.QLabel(self.frame)
        self.idle.setGeometry(QtCore.QRect(280, 320, 291, 91))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.idle.sizePolicy().hasHeightForWidth())
        self.idle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.idle.setFont(font)
        self.idle.setStyleSheet("QLabel {\n"
"    background-color: transparent; /* Membuat background transparan */\n"
"    color: white; /* Warna teks putih, bisa diganti sesuai kebutuhan */\n"
"    text-align: center; /* Memposisikan teks di tengah secara horizontal */\n"
"    qproperty-alignment: \'AlignCenter\'; /* Memposisikan teks di tengah secara vertikal dan horizontal */\n"
"}\n"
"")
        self.idle.setObjectName("idle")
        self.warnaai = QtWidgets.QComboBox(self.frame)
        self.warnaai.setGeometry(QtCore.QRect(440, 580, 171, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.warnaai.sizePolicy().hasHeightForWidth())
        self.warnaai.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.warnaai.setFont(font)
        self.warnaai.setStyleSheet("QComboBox{\n"
"border-radius:5px;\n"
"}")
        self.warnaai.setObjectName("warnaai")
        self.warnaai.addItem("")
        self.warnaai.addItem("")
        self.warnaai.addItem("")
        self.warnaai.addItem("")
        self.warnaai.addItem("")
        self.picture = QtWidgets.QLabel(self.frame)
        self.picture.setGeometry(QtCore.QRect(820, 270, 501, 301))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.picture.sizePolicy().hasHeightForWidth())
        self.picture.setSizePolicy(sizePolicy)
        self.picture.setStyleSheet("QLabel {\n"
"    border-radius: 5px;            /* Border radius 5px */\n"
"    border:1px solid;\n"
"}")
        self.picture.setFrameShape(QtWidgets.QFrame.Box)
        self.picture.setText("")
        self.picture.setObjectName("picture")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1357, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.camera.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.kata.setText(_translate("MainWindow", "Sentence:"))
        self.character.setText(_translate("MainWindow", "Character:"))
        self.camera.setItemText(0, _translate("MainWindow", "Camera Default"))
        self.camera.setItemText(1, _translate("MainWindow", "WebCam"))
        self.bahasa.setItemText(0, _translate("MainWindow", "Indonesia"))
        self.bahasa.setItemText(1, _translate("MainWindow", "Inggris"))
        self.idle.setText(_translate("MainWindow", "Kamera nonaktif"))
        self.warnaai.setItemText(0, _translate("MainWindow", "Merah"))
        self.warnaai.setItemText(1, _translate("MainWindow", "Hijau"))
        self.warnaai.setItemText(2, _translate("MainWindow", "Biru"))
        self.warnaai.setItemText(3, _translate("MainWindow", "Kuning"))
        self.warnaai.setItemText(4, _translate("MainWindow", "Ungu"))
import dlogo_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
